# Generated by Django 5.2.7 on 2025-10-08 11:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de début')),
                ('last_activity', models.DateTimeField(auto_now=True, verbose_name='Dernière activité')),
                ('mode', models.CharField(choices=[('general', 'General'), ('personal', 'Personal'), ('mixed', 'Mixed')], max_length=20, verbose_name='Mode')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Conversation',
                'verbose_name_plural': 'Conversations',
                'db_table': 'conversations',
                'ordering': ['-last_activity'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sender', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=10, verbose_name='Expéditeur')),
                ('content', models.TextField(verbose_name='Contenu')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'db_table': 'messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageReference',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('general', 'General'), ('personal', 'Personal')], max_length=20, verbose_name='Type de source')),
                ('citation', models.TextField(blank=True, null=True, verbose_name='Citation')),
            ],
            options={
                'verbose_name': 'Référence de message',
                'verbose_name_plural': 'Références de messages',
                'db_table': 'message_references',
                'ordering': ['id'],
            },
        ),
    ]
